<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\control\NodePanel.ControlPlane\NodePanel.ControlPlane.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Condition="'$(ExcludeRestorePackageImports)' != 'true'">
    <ProjectReference Include="..\..\core\NodePanel.Core\NodePanel.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuildInParallel>false</BuildInParallel>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
